### ISSUE TITLE
Fix for incorrect rotations

### ISSUE THREAD

**Issue by mikelnrd** [edwvee/exiffix#1]
Hi. I just ran the code through the 8 jpeg images of the letter F from [this blogpost](https://magnushoff.com/jpeg-orientation.html). Case 2 and 4 are incorrect - fix below for you.

```go
        case "1":
		// do nothing
	case "2":
		img = imaging.FlipH(img) // FIX: needs to be FlipH not FlipV
	case "3":
		img = imaging.Rotate180(img)
	case "4":
		img = imaging.Rotate180(imaging.FlipH(img)) // FIX: needs to be FlipH not FlipV
	case "5":
		img = imaging.Rotate270(imaging.FlipV(img))
	case "6":
		img = imaging.Rotate270(img)
	case "7":
		img = imaging.Rotate90(imaging.FlipV(img))
	case "8":
		img = imaging.Rotate90(img)
	}
```

EDIT: also I just noticed you're not handling the err returned from reader.Seek here: https://github.com/edwvee/exiffix/blob/master/decode.go#L18

**Comment by edwvee** [comment]
Thank you for correcting me. Added fix, added test.
